name: Minimum Dependencies
on: [push, pull_request]
jobs:
    mindeps:
        runs-on: ubuntu-latest
        container: python:3.6.1-slim
        steps:
        - name: Installing dependencies
          run: |
            apt-get update && apt-get install -y git &&
            pip install --upgrade pip &&
            pip install nox==2020.5.24 toml==0.10.2 poetry==1.0.9
        - uses: actions/checkout@v2
        - run: cd "$GITHUB_WORKSPACE" && nox --sessions mindeps
