name: Minimum Dependencies
on: [push, pull_request]
jobs:
    mindeps:
        runs-on: ubuntu-latest
        container: python:3.6.1-slim
        steps:
        - name: Installing dependencies
          run: |
            pip install --upgrade pip &&
            pip install nox==2022.1.7 toml==0.10.2 poetry==1.0.9
        - uses: actions/checkout@v2
        - run: |
            cd "$GITHUB_WORKSPACE" &&
            mkdir .nox &&
            nox --sessions mindeps
