name: Release
on: push
    # release:
    #     types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
              python-version: '3.9'
              architecture: x64
        - run: pip install nox==2022.1.7 toml==0.10.2 poetry==1.0.9
        - run: nox
        - run: poetry build
        - uses: actions/upload-artifact@v3
          with:
              name: dist
              path: dist/
    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        environment:
            name: pypi
            url: https://pypi.org/p/grpc-interceptor
        steps:
        - uses: actions/download-artifact@v3
          with:
              name: dist
        - name: Display artifacts
          run: ls -R
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
