name: Tests
on: [push, pull_request]
jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ['3.9']
                include:  # Oldest versions >=3.6.1 that are available for each platform
                - platform: ubuntu-20.04  # https://github.com/actions/setup-python/issues/544
                  python-version: 3.6  # Will actually use latest 3.6.x
                - platform: macos-latest
                  python-version: 3.7
                - platform: windows-latest
                  python-version: 3.7
        name: Python ${{matrix.python-version}} ${{matrix.platform}}
        runs-on: ${{matrix.platform}}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
              python-version: ${{matrix.python-version}}
              architecture: x64
        - run: pip install nox==2022.1.7 toml==0.10.2 poetry==1.0.9
        - run: nox
